In [3]:
import numpy as np

###### 1-dimensional array

In [62]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [63]:
l = [1,2,3,4,5]
a = np.array(l)
print(a)

[1 2 3 4 5]


### 2-dimensional array

In [193]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print('\n', a.shape)
print('\n', a.size)
print('\n', a.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 (3, 3)

 9

 int32


### dtype imporatance

In [54]:
x = np.array([[1, 2.5, 3.5, 4]])
print(x.dtype)
print(x)

float64
[[1.  2.5 3.5 4. ]]


In [195]:
x = np.array([1, 2.5, 3.5, 4], dtype=np.int64)
print(x.dtype)
print(x)

int64
[1 2 3 4]


###### all elmemsts will be same data type

In [68]:
a = np.array([1, 2, 'n', 4, 5])
print(a)

['1' '2' 'n' '4' '5']


###### built in functions in numpy

##### linspace()

In [55]:
x = np.linspace(1,5,10, dtype=np.int64)
print(x)

[1 1 1 2 2 3 3 4 4 5]


In [69]:
a = np.linspace(1, 5, 10, True, False)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [70]:
a = np.linspace(1, 5, 10, False, True)
print(a)

(array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6]), 0.4)


###### arange

In [71]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [73]:
a = np.arange(4, 10)
print(a)

[4 5 6 7 8 9]


In [10]:
a = np.arange(1, 10, 2)
print(a)

[1 3 5 7 9]


###### ones(): careful with brackets

In [12]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [74]:
a = np.ones((4,4), dtype=np.int64)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


###### zeros

In [18]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


###### random numbers: here no double paranthesis

In [6]:
a = np.random.rand(3,3)
print(a)

[[0.93376928 0.20370683 0.81306707]
 [0.18859869 0.563409   0.23072827]
 [0.51597778 0.7354096  0.70598164]]


In [11]:
x = np.random.random((3,3))
print(x)

[[0.99345653 0.04393562 0.42792699]
 [0.09955982 0.12752605 0.52364406]
 [0.48352902 0.08582552 0.5128579 ]]


In [16]:
x = np.random.randint(1,10, size=(10,))
print(x)

[8 2 6 6 1 3 6 1 1 9]


In [200]:
x = np.random.randint(1,10, size=(3,3))
print(x)

[[9 1 5]
 [4 1 2]
 [7 5 6]]


In [102]:
x = np.random.normal(0, 0.1, size = (1000,1000))
print(x)

[[ 0.06904841  0.07074475 -0.02808792 ...  0.14795191 -0.07920965
   0.00774628]
 [ 0.04146168  0.17708592 -0.12022235 ... -0.21578502 -0.08556144
   0.01891094]
 [-0.07070737  0.03938515 -0.10402198 ...  0.01894348  0.12017918
  -0.06361417]
 ...
 [ 0.00083045  0.01872044  0.10735496 ... -0.16329062 -0.10045094
  -0.05729936]
 [-0.09776389  0.18012155 -0.11055897 ...  0.14461572  0.0420088
   0.06321927]
 [ 0.13766935  0.0662921  -0.01952086 ...  0.10047073 -0.1788429
  -0.03168528]]


###### logspace()

In [20]:
a = np.logspace(1, 5, 10, True, 10.0)
print(a)

[1.00000000e+01 2.78255940e+01 7.74263683e+01 2.15443469e+02
 5.99484250e+02 1.66810054e+03 4.64158883e+03 1.29154967e+04
 3.59381366e+04 1.00000000e+05]


###### ***timeit; getsizeof(); itemsize

In [128]:
import time

start = time.time()

x = range(1000)
y = sum(x)
print(y)

print(time.time() - start)

499500
0.0009999275207519531


In [24]:
import timeit

x = range(1000)
y = np.array(x)
timeit.timeit(np.sum(y))

ValueError: stmt is neither a string nor callable

In [70]:
x = range(10)

y = np.array(x)
print(y)

r = y.itemsize * y.size
print(r)

[0 1 2 3 4 5 6 7 8 9]
40


In [26]:
import sys

x = range(1000)
print(x)
print(sys.getsizeof(x))# sys-system specific parameter

range(0, 1000)
48


In [59]:
y = sys.getsizeof(1) * len(x) #list
print(y)

280


### reshape

In [75]:
x = np.arange(20) #20 is stop value
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [76]:
y = np.reshape(x, (4, 5))
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [77]:
y = np.reshape(x, (10, 2))
print(y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [203]:
b = np.array([10,11,12])
print(b)

[10 11 12]


In [202]:
b = np.array([10,11,12]).reshape(3,1)
print(b)

[[10]
 [11]
 [12]]


In [80]:
x = np.linspace(0, 50, 10, endpoint=True).reshape(5,2)
print(x)

[[ 0.          5.55555556]
 [11.11111111 16.66666667]
 [22.22222222 27.77777778]
 [33.33333333 38.88888889]
 [44.44444444 50.        ]]


In [81]:
a = np.arange(1, 10).reshape(3,3) #useful many times
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [82]:
a.shape

(3, 3)

###### Numpy operations

In [150]:
x = np.array([1,2,3,4,5,6]) #1d array or rank 1 array
y = np.array([1,2,3,4,5,6])

print(x+y)
print(np.add(x, y))

[ 2  4  6  8 10 12]
[ 2  4  6  8 10 12]


In [205]:
array_1 = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(array_1, end = "\n\n")

array_2 = np.arange(10,19).reshape(3,3)

print(array_2, end = "\n\n")

result = np.add(array_1, array_2)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[10 11 12]
 [13 14 15]
 [16 17 18]]

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [206]:
result = np.subtract(array_1, array_2)
print(result)

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [211]:
result = np.subtract(array_2, array_1)
print(result)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [207]:
result = np.multiply(array_1, array_2)
print(result)

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [208]:
result = np.divide(array_1, array_2)
print(result)

[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]


In [97]:
result = np.divide(array_2, array_1) #1st argument: dividend; 2nd argument: divisor

print(array_2)

print(array_1)

print(result)

[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10.          5.5         4.        ]
 [ 3.25        2.8         2.5       ]
 [ 2.28571429  2.125       2.        ]]


In [209]:
result = np.remainder(array_1, array_2)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [210]:
result = np.remainder(array_2, array_1)
print(result)

[[0 1 0]
 [1 4 3]
 [2 1 0]]


In [165]:
x = np.array([1,2,3,4])
print(np.sqrt(x))

[1.         1.41421356 1.73205081 2.        ]


In [166]:
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [167]:
print(np.power(x,2))

[ 1  4  9 16]


Statistical functions

In [171]:
x = np.array([1,2,3,4]).reshape(2,2)
print(x, '\n')
print(x.mean())

[[1 2]
 [3 4]] 

2.5


In [175]:
print("average of columns:", x.mean(axis=0))

average of columns: [2. 3.]


In [176]:
print("average of rows:", x.mean(axis=1))

average of columns: [1.5 3.5]


In [177]:
print(x.sum())
print("sum of columns:", x.sum(axis=0))
print("sum of rows:", x.sum(axis=1))

10
sum of columns: [4 6]
sum of rows: [3 7]


In [178]:
print(x.max())

4


In [179]:
print(x.min())

1


In [180]:
print(x.std())

1.118033988749895


adding or subtracting one element to each element in numpy array

In [181]:
print(x+2)

[[3 4]
 [5 6]]


In [182]:
print(x-2)

[[-1  0]
 [ 1  2]]


In [183]:
print(x/2)

[[0.5 1. ]
 [1.5 2. ]]


In [188]:
print(x%2)

[[1 0]
 [1 0]]


adding 1d and 2d

In [190]:
y = np.arange(1,10).reshape(3,3)

print(y, '\n')

x = np.arange(3)

print(x, '\n')

print(y+x)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[0 1 2] 

[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


In [192]:
y = np.arange(1,10).reshape(3,3)

print(y, '\n')

x = np.arange(3).reshape(3,1)

print(x, '\n')

print(y+x)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[0]
 [1]
 [2]] 

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


### accessing the components of array

In [98]:
a = np.arange(1,10).reshape(3,3)

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [99]:
print(a[0,1])

2


first row

In [100]:
print(a[0,:])

[1 2 3]


first column

In [101]:
print(a[:,0])

[1 4 7]


second and third rows

In [102]:
print(a[1:3])

[[4 5 6]
 [7 8 9]]


In [22]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [27]:
print("1st element:", x[0])
print("2nd element:", x[1])
print("5th element:", x[4])

1st element: 1
2nd element: 2
5th element: 5


In [28]:
print("1st element:", x[-5])
print("2nd element:", x[-4])
print("5th element:", x[-1])

1st element: 1
2nd element: 2
5th element: 5


In [214]:
a = np.arange(1,21).reshape(4,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [85]:
indices = np.array([1,3])
print(indices)

[1 3]


In [86]:
b = a[indices, :]
print(b)

[[ 6  7  8  9 10]
 [16 17 18 19 20]]


In [88]:
c = a[:, indices]
print(c)

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


###### subset of arrays

In [217]:
a = np.arange(1,10).reshape(3,3)

print(a, '\n')

a_sub = a[:2, :2]
print(a_sub)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2]
 [4 5]]


modifying the subset by index number

In [105]:
a_sub[0,0] = 24
print(a_sub)

[[24  2]
 [ 4  5]]


In [106]:
print(a)

[[24  2  3]
 [ 4  5  6]
 [ 7  8  9]]


###### modify using the built in methods

###### Transpose

In [107]:
print(np.transpose(a))

[[24  4  7]
 [ 2  5  8]
 [ 3  6  9]]


###### append

In [108]:
result = np.append(a,[[10,11,12]], axis=0)
print(result)

[[24  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [109]:
b = np.arange(10,13).reshape(3,1)

result = np.append(a, b, axis=1)
print(result)

[[24  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


###### Insert

In [61]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
b = np.arange(10,13).reshape(1,3)
print('\n', b)
result = np.insert(a,1,b,axis=0)
print('\n', result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[10 11 12]]

 [[ 1  2  3]
 [10 11 12]
 [ 4  5  6]
 [ 7  8  9]]


In [218]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
b = np.arange(10,13).reshape(1,3)
print(b)
result = np.insert(a,1,b,axis=1)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]]
[[ 1 10  2  3]
 [ 4 11  5  6]
 [ 7 12  8  9]]


In [122]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
b = np.arange(10,13).reshape(3,1)
print(b)
result = np.insert(a,1,b,axis=0)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10]
 [11]
 [12]]
[[ 1  2  3]
 [10 10 10]
 [11 11 11]
 [12 12 12]
 [ 4  5  6]
 [ 7  8  9]]


In [52]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
b = np.array([10,11,12]).reshape(3,1)
print('\n',b)
result = np.insert(a,1,b,axis=1)
print('\n',result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[10]
 [11]
 [12]]

 [[ 1 10 11 12  2  3]
 [ 4 10 11 12  5  6]
 [ 7 10 11 12  8  9]]


###### Delete()

In [124]:
a_del = np.delete(a, 1, axis=0)
print(a_del)

[[1 2 3]
 [7 8 9]]


In [125]:
a_del = np.delete(a, 1, axis=1)
print(a_del)

[[1 3]
 [4 6]
 [7 9]]


In [35]:
x = np.array([1,2,3,4,5,6]) #1d delete
y = np.delete(x, (0,4)) #0, 4 are indexes
print(y)

[2 3 4 6]


# Notes from Udacity

#### save and load a numpy array

In [2]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
np.save('my_array',x) #'my_array' is file name in which numpy array is stored

In [3]:
y = np.load('my_array.npy')
print(y)

[1 2 3 4 5]


###### Identity matrix and diagonal matrix

In [8]:
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [27]:
x = np.eye(5, dtype=np.int64) #identity matrix
print(x)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [29]:
y = np.diag([10,20,30,40,50])
print(y)

[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


In [58]:
a = np.arange(1,21).reshape(4,5)
print(a)
d = np.diag(a) 
print('\n', d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

 [ 1  7 13 19]


In [59]:
d = np.diag(a, k=1)
print(d)

[ 2  8 14 20]


In [60]:
d = np.diag(a, k=-1)
print(d)

[ 6 12 18]


###### Vstack and Hstack

In [90]:
x = np.array([1,2])
print(x)

[1 2]


In [91]:
y = np.array([[3,4],[5,6]])
print(y)

[[3 4]
 [5 6]]


In [92]:
z = np.vstack((x, y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [93]:
w = np.hstack((y, x.reshape(2,1)))
print(w)

[[3 4 1]
 [5 6 2]]


###### copy()

In [33]:
import numpy as np

In [34]:
a = np.arange(1,21).reshape(4,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [39]:
b = np.copy(a)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [40]:
b[1, 3] = 180
print(b)

[[  1   2   3   4   5]
 [  6   7   8 180  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]


In [17]:
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [36]:
b = np.copy(a[1:, 2:])
print(b)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [41]:
c = a[1:, 2:].copy()
print(c)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [21]:
c[2,2] = 555
print(c)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [22]:
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [94]:
d = np.copy(a[1:, 1:4])
print(d)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


###### unique

In [105]:
u = np.array([[1,2,3], [4,2,3], [8,1,9]])
print(u)
result = np.unique(u)
print('\n', result, '\n', )
print(np.reshape(result,(6,1)))

[[1 2 3]
 [4 2 3]
 [8 1 9]]

 [1 2 3 4 8 9] 

[[1]
 [2]
 [3]
 [4]
 [8]
 [9]]


###### Boolean indexing

In [106]:
X = np.arange(25).reshape(5,5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [113]:
print(X[X>10])

print('\n', X[X>9].reshape(5,3))

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]

 [[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]


In [114]:
print(X[X<7])

[0 1 2 3 4 5 6]


In [118]:
print(X[(X>10) & (X<17)])

[11 12 13 14 15 16]


In [120]:
X[(X>10) & (X<17)] = -1
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


###### Set operations

In [121]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])

print(np.intersect1d(x,y))
print(np.setdiff1d(x,y))
print(np.union1d(x,y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


In [125]:
x = np.array([1,2,3,4,5,5]).reshape(3,2)
y = np.array([6,7,2,8,4,9]).reshape(3,2)
print(np.intersect2d(x,y))

AttributeError: module 'numpy' has no attribute 'intersect2d'

###### sort()

In [43]:
x = np.random.randint(1,11, size = (10,))
print(x, '\n')

y = np.sort(x) #sort() used as a function, will not modify original numpy array
print(y, '\n')

z = np.sort(np.unique(x))
print(z, '\n')

print(x)

[8 5 8 5 3 1 3 9 1 1] 

[1 1 1 3 3 5 5 8 8 9] 

[1 3 5 8 9] 

[8 5 8 5 3 1 3 9 1 1]


In [48]:
x.sort() #sort() used as a method will modify original numpy array
print(x)

[1 1 1 3 3 5 5 8 8 9]


###### sort rank 2 array

In [51]:
x = np.random.randint(1, 26, size=(5,5))
print(x)

[[19 11  9 15 20]
 [ 3 23 23  9  3]
 [11 19 15  8  9]
 [25  9 13  7  6]
 [ 1 10 10 23 19]]


In [52]:
y = np.sort(x, axis=0) #sort by rows
print(y)

[[ 1  9  9  7  3]
 [ 3 10 10  8  6]
 [11 11 13  9  9]
 [19 19 15 15 19]
 [25 23 23 23 20]]


In [53]:
y = np.sort(x, axis=1)
print(y)

[[ 9 11 15 19 20]
 [ 3  3  9 23 23]
 [ 8  9 11 15 19]
 [ 6  7  9 13 25]
 [ 1 10 10 19 23]]


Practice

In [4]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
x = np.full(3,4,1,5)
print(x)

TypeError: data type not understood